//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.10.15 at 10:09:12 PM NOVT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://degtyar.ru/springboot/soap/person", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package ru.degtyar.springboot.soap.person;
